// source : https://xiaoguan.gitbooks.io/leetcode/content/LeetCode/321-create-maximum-number-hard.html
//

// it's simple, from each array, create a stack of size k, get top 5 elements...
// merge the two stack to get the maximum numbers from them...
//
