//The first term is "1"
//
//Second term is "11", generated by reading first term as "One 1" 
//(There is one 1 in previous term)
//
//Third term is "21", generated by reading second term as "Two 1"
//
//Fourth term is "1211", generated by reading third term as "One 2 One 1" 
//
//and so on



#include<iostream>
#include<vector>
#include<string>
#include<cstdlib>

using namespace std;

void recusrion(string &str, int &itr, int input) {
	if(itr >= input) { cout << str << endl; return; }

	string tmp = "";
	int length = str.size();
	int index=1;
	while(index <= length) {
		int count = 1; 
		while(str[index] == str[index-1]) {count++; index++; }
		
		tmp += to_string(count);
		tmp += str[index-1];
		index++;
		
	}
	str = tmp;
	itr += 1;
	recusrion(str, itr, input);
}


int main() {
	string str = "1";
	int input = 4, itr = 1;
	recusrion(str, itr, input);

}
